server:
  port: 8085
spring:
  datasource:
    driver-class-name: org.h2.Driver #com.mysql.cj.jdbc.Driver
    url: jdbc:h2:mem:testdb #jdbc:mysql://localhost:3306/db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    info:
      enabled: true
